#!/bin/bash
 
my_pid=$$
echo "My process ID is $my_pid"

echo "Launching roscore..."
roscore &
pid=$!
sleep 5s

echo "Launching Gazebo..."
roslaunch drdo_gazebo drdo_world.launch &
pid="$pid $!"

sleep 5s

echo "Launching publishers..."
rosrun drdo_ros drdo_tf_broadcaster &
pid="$pid $!"

rosrun drdo_ros drdo_odom_publisher &
pid="$pid $!"

# sleep 3s

# echo "Launching Rviz..."
# roslaunch drdo_description drdo_rviz.launch &

sleep 3s

echo "Launching drdo controller..."
rosparam load "$(rospack find drdo_ros)/pioneer_controller_params.yaml" drdo_ros &

sleep 1s

rosrun drdo_ros drdo_pid_controller &
pid="$pid $!"

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h
