controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - shoulder_roll_joint
      - shoulder_pitch_joint
      - shoulder_yaw_joint
      - elbow_pitch_joint
      - elbow_yaw_joint
      - wrist_pitch_joint
      - wrist_roll_joint
  - name: gripper_controller
    type: GripperCommand
    action_ns: gripper_action
    default: true
    parallel: true
    joints:
      - l_gripper_finger_joint
      - r_gripper_finger_joint