controller_list:
  - name: fake_arm_controller
    joints:
      - shoulder_roll_joint
      - shoulder_pitch_joint
      - shoulder_yaw_joint
      - elbow_pitch_joint
      - elbow_yaw_joint
      - wrist_pitch_joint
      - wrist_roll_joint
  - name: fake_gripper_controller
    joints:
      - l_gripper_finger_joint
      - r_gripper_finger_joint