controller_gains:
    left:
        linear:
            p: 10.87
            i: 0.01
            d: 0.1
        angular:
            p: 3.37
            i: 0.01
            d: 0.1
    right:
        linear:
            p: 10.87
            i: 0.01
            d: 0.1
        angular:
            p: 3.37
            i: 0.01
            d: 0.1
    body:
        linear:
            p: 0.70
            i: 0.01
            d: 0.1
        angular:
            p: -1.00
            i: 0.01
            d: 0.1
pioneer:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50  


    # Position Controllers ---------------------------------------
    shoulder_roll_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: shoulder_roll_joint
        pid: {p: 10.0, i: 0.01, d: 0.1}

    shoulder_pitch_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: shoulder_pitch_joint
        pid: {p: 10.0, i: 0.01, d: 0.1}

    shoulder_yaw_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: shoulder_yaw_joint
        pid: {p: 10.0, i: 0.01, d: 0.1}

    elbow_pitch_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: elbow_pitch_joint
        pid: {p: 10.0, i: 0.01, d: 0.1}    

    elbow_yaw_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: elbow_yaw_joint
        pid: {p: 10.0, i: 0.01, d: 0.1}

    wrist_pitch_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: wrist_pitch_joint
        pid: {p: 10.0, i: 0.01, d: 0.1}

    wrist_roll_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: wrist_roll_joint
        pid: {p: 10.0, i: 0.01, d: 0.1}
        
    gripper_joint1_position_controller:
        type: effort_controllers/JointPositionController
        joint: gripper_joint1
        pid: {p: 10.0, i: 0.01, d: 0.1}
    gripper_joint2_position_controller:
        type: effort_controllers/JointPositionController
        joint: gripper_joint2
        pid: {p: 10.0, i: 0.01, d: 0.1}
